services:
  oracle-12ee:
    image: oracle/database:12.2.0.1-ee
    container_name: oracle-12ee
    ports:
      - "1521:1521" # Puerto para Oracle Database
      - "5500:5500" # Puerto para Oracle Enterprise Manager Express(OEM express)
    environment:
      ORACLE_PWD: Pelota12* # Contraseña para el usuario SYS/SYSTEM
      #ORACLE_SID=BI
      ORACLE_PDB: BIUMSA
      ORACLE_CHARACTERSET: AL32UTF8
      TZ: America/La_Paz
    volumes:
      - ./oradata:/opt/oracle/oradata # Para persistencia de datos
  obiee-12:
    image: oracle/biplatform:12.2.1.3
    container_name: obiee-12
    ports:
      - "9500:9500"
      - "9502:9502"
    environment:
      ADMIN_USERNAME: weblogic
      ADMIN_PASSWORD: orawl1234
      DB_HOST: oracle-12ee
      DB_PORT: 1521
      DB_SERVICE: BIUMSA
      DB_USERNAME: sys
      DB_PASSWORD: Pelota12*
      SCHEMA_PREFIX: DEV
      SCHEMA_PASSWORD: devPassword12
      WEBLOGIC_CLASSPATH: "$ORACLE_HOME/wlserver/server/lib/weblogic.jar"
    depends_on:
      oracle-12ee:
        condition: service_healthy
        restart: true
    entrypoint: ["/bin/bash", "-c", "echo Pelota12* | /u01/wait_for_db.sh /u01/oracle/ sys oracle-12ee 1521 BIUMSA && /u01/createAndStartDomain.sh"]