version: '3'
services:
  oracle-21se:
    image: oracle/database:21.3.0-se2
    container_name: oracle-21se
    ports:
       # port:port_docker
      - "1522:1521" # Puerto para Oracle Database
      - "5501:5500" # Puerto para Oracle Enterprise Manager
    environment:
      - ORACLE_PDB=PDBACUARIO  # Nombre del pluggable database
      - ORACLE_PWD=pelota12*     # Contraseña para el usuario SYS/SYSTEM
      - INIT_SGA_SIZE=3000      # Tamaño de SGA (Shared Global Area) en MB
      - INIT_PGA_SIZE=1000      # Tamaño de PGA (Program Global Area) en MB
      - TZ=America/La_Paz
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - ./oradata:/opt/oracle/oradata # Directorio para persistencia de datos
      - ./backup/:/home/oracle/backup # Directorio para persistencia de datos