apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
data:
  #decode admtest
  username: YWRtdGVzdA==
  #decode pelota12
  password: cGVsb3RhMTI=
#Codificado por base 64

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database
data:
  db_host: oracle21c
  oracle_pdb: pdbtest
  oracle_characterset: AL32UTF8
  tz: America/La_Paz
  init_sga_size: "3000"
  init_pga_size: "1000"
  #secret password

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
data:
  # username: root
  # password: "123456"
  backend.yml: |-
    config:
      texto: Configurando ambiente por defecto
    ---
    spring:
      config:
        activate:
          on-profile: dev
    config:
      texto: Configurando ambiente de desarrollo
    ---
    spring:
      config:
        activate:
          on-profile: prod
    config:
      texto: Configurando ambiente de produccion
