apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle21c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle21c
  template:
    metadata:
      labels:
        app: oracle21c
    spec:
      containers:
        - image: edualdan982/oracle-db:21.3.0-ee
          name: oracle21c
          # volumeMounts:
          #   - name: data-oracle
          #     mountPath: /opt/oracle/oradata
          ports:
            - containerPort: 1521
            - containerPort: 5550
          env:
            - name: ORACLE_PDB
              value: 'PDBTEST'
              # valueFrom:
              #   configMapKeyRef:
              #     name: database
              #     key: oracle_pdb
            - name: ORACLE_PWD
              value: 'Pelota12%'
              # valueFrom:
              #   secretKeyRef:
              #     name: database
              #     key: password
            - name: INIT_SGA_SIZE
              value: '3000'
              # valueFrom:
              #   configMapKeyRef:
              #     name: database
              #     key: init_sga_size
            - name: INIT_PGA_SIZE
              value: '1000'
              # valueFrom:
              #   configMapKeyRef:
              #     name: database
              #     key: init_pga_size
            - name: ORACLE_CHARACTERSET
              value: 'AL32UTF8'
              # valueFrom:
              #   configMapKeyRef:
              #     name: database
              #     key: oracle_characterset
            - name: TZ
              value: 'America/La_Paz'
              # valueFrom:
              #   configMapKeyRef:
              #     name: database
              #     key: tz
          resources:
            limits:
              cpu: ''
              memory: '512Mi'
            cpu: '500m'
            requests:
              cpu: '250m'
              memory: '2Gib'
      # volumes:
      #   - name: data-oracle
      #     persistentVolumeClaim:
      #       claimName: oracle-pvc
