apiVersion: v1
kind: Service
metadata:
  name: oracle21c
spec:
  ports:
  - port: 1521
    protocol: TCP
    targetPort: 1521
  - port: 5500
    protocol: TCP
    targetPort: 5500
  selector:
    app: oracle21c
  type: ClusterIP