apiVersion: v1
kind: Service
metadata:
  name: oracle21c
spec:
  ports:
  - name: sqlnet
    port: 1521
    protocol: TCP
    targetPort: 1521
  - name: downsql
    port: 5500
    protocol: TCP
    targetPort: 5500
  selector:
    app: oracle21c
  type: ClusterIP