# Declaración del Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bd
  name: oracle-19se-svc
  namespace: financieros
spec:
  type: NodePort
  ports:
    - name: sqlnet
      port: 1521
      protocol: TCP
      targetPort: 1521
    - name: downsql
      port: 5500
      protocol: TCP
      targetPort: 5500
  selector:
    app: oracle-19se
---
# Declaración del StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: bd
  name: oracle-19se
  namespace: financieros
spec:
  serviceName: 'oracle-19se-svc'
  replicas: 1
  selector:
    matchLabels:
      app: oracle-19se
  template:
    metadata:
      labels:
        app: oracle-19se
    spec:
      automountServiceAccountToken: false
      containers:
        - image: edualdan982/oracle-db:19.3.0-se2
          name: oracle-19se
          imagePullPolicy: Always
          resources:
            requests:
              memory: '4Gi'
              cpu: '4'
            limits:
              memory: '8Gi'
              cpu: '6'
          volumeMounts:
            - name: data-oracle-19se
              mountPath: /opt/oracle/oradata
          ports:
            - containerPort: 1521
              name: sqlnet
            - containerPort: 5500
              name: downsql
          env:
            - name: ORACLE_PDB
              value: FI_PDB
            - name: ORACLE_PWD
              valueFrom:
                secretKeyRef:
                  name: oracle-secret
                  key: password
            - name: INIT_SGA_SIZE
              value: "3000"
            - name: INIT_PGA_SIZE
              value: "1000"
            - name: ORACLE_CHARACTERSET
              value: "AL32UTF8"
            - name: TZ
              value: "America/La_Paz"
      volumes:
        - name: data-oracle-19se
          hostPath:
            path: /vol/financieros/oradata-19se
            type: Directory
      imagePullSecrets:
        - name: edualdan982-secret
      nodeName: n2
