# Declaracion del service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bd
  name: oracle-19c-svc
  #namespace: financieros
spec:
  #type: NodePort
  ports:
    - name: sqlnet
      port: 1521
      protocol: TCP
      targetPort: 1521
    - name: downsql
      port: 5500
      protocol: TCP
      targetPort: 5500
  clusterIP: None  # Requerido para StatefulSets
  selector:
    app: oracle-19c
---
# Declaracion del StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: bd
  name: oracle-19c
  #namespace: financieros
spec:
  serviceName: 'oracle-19c-svc'
  replicas: 1
  selector:
    matchLabels:
      app: oracle-19c
  template:
    metadata:
      labels:
        app: oracle-19c
    spec:
      #automountServiceAccountToken: false
      containers:
        # - image: oracle/database:19.3.0-se2
        - image: oracle/database:19.3.0-ee
          name: oracle-19c
          volumeMounts:
            - name: oracle-data-19c
              mountPath: /opt/oracle/oradata
          ports:
            - containerPort: 1521
              name: sqlnet
            - containerPort: 5550
              name: downsql
          env:
            - name: ORACLE_PDB
              value: FI_PDB
            - name: ORACLE_PWD
              valueFrom:
                secretKeyRef:
                  name: oracle-secret
                  key: password
            - name: INIT_SGA_SIZE
              value: '3000'
            - name: INIT_PGA_SIZE
              value: '1000'
            - name: ORACLE_CHARACTERSET
              value: 'AL32UTF8'
            - name: TZ
              value: 'America/La_Paz'
      terminationGracePeriodSeconds: 30
      # imagePullSecrets:
      #   - name: edualdan982-secret
  volumeClaimTemplates:
    - metadata:
        name: oracle-data-19c
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 20Gi
